# Generated by Django 4.2.16 on 2024-10-03 20:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
