# Generated by Django 4.2.16 on 2024-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='temporary_field',
        ),
    ]
