# Generated by Django 4.2.16 on 2024-10-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_category_alter_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
