# Generated by Django 4.2.16 on 2024-10-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
