# Generated by Django 4.2.16 on 2024-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_user_comment_author_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('opinion', 'Opinion'), ('recommendation', 'Recommendation'), ('discussion', 'Discussion'), ('rant', 'Rant'), ('gadgets/tech', 'Gadgets/Tech'), ('hobbies', 'Hobbies'), ('writers', 'Writers'), ('misc', 'Miscellaneous')], default='discussion', max_length=50),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
