# Generated by Django 4.2.16 on 2024-10-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_post_category_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('opinion', 'Opinion'), ('rec', 'Recommendation'), ('disc', 'Discussion'), ('rant', 'Rant'), ('gtech', 'Gadgets & Tech'), ('hobbies', 'Hobbies'), ('writers', 'Writers'), ('misc', 'Miscellaneous')], default='discussion', max_length=50),
        ),
    ]
